### ISSUE TITLE
Don't forget to update version info in `package.xml` 

### ISSUE THREAD

**Issue by luzpaz** [Simturb/Beltrami#29]

**Comment by Simturb** [comment]
Done. Thanks.

**Comment by luzpaz** [comment]
BTW, you can programmatically access the version number via python.... 

@chennes is there a python schema somewhere showing how to access package.xml pythonically to ascertain an addons version ? (i just did a search and couldn't find documentation code to do this)

**Comment by chennes** [comment]
Yes, the Python wrapper for Metadata is basically complete: you just need the "Version" data element, so something like:
```
import FreeCAD
md = FreeCAD.Metadata("/path/to/package.xml")
print(md.Version)
```

**Comment by luzpaz** [comment]
Thanks @chennes! Would be great to have this documented on the wiki. Is it documented somewhere?

**Comment by chennes** [comment]
It should be in the auto-generated Python binding docs -- I don't know where those live, though.

**Comment by Simturb** [comment]
Chris, When I download the WB from the Addon Manager, I desinstall the release 1.0.7 then I install 1.0.8. It seems to work but I got the message  I click OK. In fact, Curves wb is up to date.Then I got :  So it seems to work but I need to restart FreeCADAnd if I go back to the Addon manager :  The version number is not the good one!!However, Inside Beltrami I display the version number and it is the good one.    So maybe I made a mistake somewhere, on there is a bug. Thanks for your help. Michel  www.simturb.com De : Chris HennesEnvoyé le :4 novembre 2022 12:30À : Simturb/BeltramiCc : SimTurb; MentionObjet :Re: [Simturb/Beltrami] Don't forget to update version info in `package.xml` (Issue #29) It should be in the auto-generated Python binding docs -- I don't know where those live, though.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by chennes** [comment]
There is some issue with the way the version number information is cached, I think.
